import useCurrentSong from "./hooks/use-current-song.js";
import useIsPlaying from "./hooks/use-is-playing.js";
import Auth from "./modules/auth.js";
import MusicKit from "./modules/music-kit.js";
import Player from "./modules/player.js";
export type { IPlaybackState } from "./types/playback-state.js";
export * from "./types/song.js";
export * from "./types/playback-status.js";
export * from "./types/catalog-search.js";
export * from "./types/auth-status.js";
export * from "./types/check-subscription.js";
export * from "./types/music-item.js";
export * from "./types/tracks-from-library.js";
export { useCurrentSong, useIsPlaying, Auth, Player, MusicKit };
